language: ruby

rvm:
  - 2.2
before_script:
  - cp config/database.example.yml config/database.yml
  - cp config/secrets.example.yml config/secrets.yml
script:
  - RAILS_ENV=test bundle exec rake db:create
  - bundle exec rake db:migrate --trace
  - bundle exec rake test_with_coveralls
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"